# 并发3-取消任务


## 取消

拥有取消一个异步操作的能力，在几乎所有程序中都是很常见的需求。再一次，和错误处理一样，在传统的基于 completion handler 的代码中，想要实现取消是很困难的。用 Async/Await 部分的 loadFirstPosterCont 函数为例，想要支持取消，我们所需要的变更有：”

+ 为调用者提供一种方法，来让它能够发出信号表示操作已经取消。
+ 当取消令牌接受到取消请求时，取消掉 URL Session 的操作。
+ 注意不要在任务已经被取消后再去开始新的任务。
+ 确保在取消时向调用者返回一个合适的错误码。

早先我们已经看到 Swift 的并发系统是协作式的，这一点对取消也同样适用：除非在任务中运行的代码周期性地检查取消状态，并在需要时提前结束，否则取消一个任务将不会带来任何影响。对于这套系统来说，一个很重要的设计目标是为函数提供机会，让它们能在取消时进行清理。这也是系统不能单纯地中断一个被取消的任务的原因。

在最基本的层面上，取消一个任务所做的事情，仅只是设置任务元数据上的一个标志。某个函数如果想要支持取消，它就需要偶尔对 Task.isCancelled 进行检查，或者去调用 try Task.checkCancellation()，后者会在 isCancelled 是 true 时直接抛出一个何时的错误。为我们的示例函数加上这些检查后，代码如下：

```
func loadFirstPoster2() async throws -> Data {
	try Task.checkCancellation()//检查取消任务
	let session = URLSession.shared
	let (data, _) = try await session.data(from: Episode.url)
	try Task.checkCancellation()//检查取消任务
	let episodes = try JSONDecoder().decode([Episode].self, from: data)
	try Task.checkCancellation()//检查取消任务
	return try await session.data(from: episodes[0].poster_url).0
}
```

值得注意的是，就算 JSONDecoder 是一个完全同步的 API，它也是可以支持取消的。同步函数也能用同样的 Task.isCancelled 或 try Task.checkCancellation() 调用来检查取消，如果同步函数是内嵌在一个异步上下文中时，这些方式将会按正确的方式运行；而如果在同步上下文中的话，它们会返回默认值 (比如 false)。

如果是在异步函数中，我们也会想要以同样的方式定期调用 Task.yield()，以便让运行时有机会在我们的线程上安排其他任务运行。

按照惯例，一个函数如果检测到自己被取消了，它应该抛出 CancellationError 这个标准库中的新类型。调用者可以通过检查这个错误来把取消操作和其他错误区分开来。使用这个取消错误的好处是，它不会引入新的控制流路径，但是要注意，对这个特定错误的使用只是一个惯例：调用者不能完全依赖这个类型。比如，URLSession 在被取消时会继续按照以前的方式抛出 URLError.Code.cancelled 错误。如果我们不想把这个 URLSession 的行为暴露给调用者的话，我们可以捕获这个“出错的”错误类型，把它替换成 CancellationError：
```
func loadFirstPoster3() async throws -> Data {
	do {
		let session = URLSession.shared
		let (data, _) = try await session.data(from: Episode.url)
		let episodes = try JSONDecoder().decode([Episode].self, from: data)
		return try await session.data(from: episodes[0].poster_url).0
	} catch URLError.Code.cancelled {
		// Replace URLError.Code.cancelled.
		throw CancellationError()
	} catch {
		// Propagate all other errors.
		throw error
	}	
}
```


## 取消和结构化并发

到目前为止，我们已经看到了单个任务中的取消，但是取消系统的真正威力，在于它和结构化并发的整合。取消信号会自动沿着任务树向下流动：当一个父任务被取消时，它的子任务会看到它们的 isCancelled 标志被切换为了 true。同样地，这不会让子任务立即停止，每个任务都要负责自己执行定期的取消检查。此外，取消必须尊重结构化并发的基本规则，也就是子任务不能超出父任务的生命周期，被取消的父任务会继续保持运行，直到它的所有子任务都完成为止。

```
func asyncWithTimeout<R>(
	nanoseconds timeout: UInt64,
	do work: @escaping () async throws -> R
) async throws -> R {
	return try await withThrowingTaskGroup(of: R.self) { group in

		// 开始实际工作
		group.addTask { try await work() }
		// 开始超时计时
		group.addTask {
			try await Task.sleep(nanoseconds: timeout)
			// 超时
			throw CancellationError()
		}
		// 第一个到达的胜出，取消其他任务
		let result = try await group.next()!
		group.cancelAll()
		return result
	}
}

// 如果下载任务用时超出一秒，这个函数将以 CancellationError 终止：”
let imageData = try await asyncWithTimeout(nanoseconds: 1_000_000_000, 
do: loadFirstPoster3)

```

在 asyncWithTimeout 中，我们使用了一个任务组来开始两个并发子任务：一个进行实际工作，另一个按照需要的超时时间进行休眠。然后我们开始等待第一个完成的子任务。如果负责实际工作的任务“获胜”的话，我们就把它的结果返回，并取消掉超时任务。如果超时任务更快完成，那么 group.next() 将会抛出 CancellationError。因为任务组由于错误退出了，它将会隐式地将未完成工作任务取消掉。

在获取第一个结果后的 group.cancelAll() 调用十分重要，这是因为任务组并不会在成功完成时隐式取消掉还没有等待的子任务。如果没有 cancelAll()，那么任务组就会在返回前默默等待负责超时的任务执行到结束。忘掉这一行是一个非常常见的错误，因为它并不会改变你的程序的输出结果，而只会影响性能.


## 取消处理程序

`withTaskCancellationHandler(operation:onCancel:) `函数让我们可以为当前任务指定一个取消时运行的处理程序 (cancellation handler)。这个函数接受两个闭包：一个是运行在当前任务中的异步操作 (工作)；另一个则是在当前任务被取消时会被立即调用的取消处理程序。这段处理程序的目的，是为了在取消时执行一些清理代码，比如说释放资源或者把取消信号传递给那些和 Swift 并发系统尚未整合的其他对象。


## 非结构化并发 (未完待续)

有时，限制在一个范围内的结构化并发的特征反而会变成一种障碍。我们需要另一种工具，来让我们可以退出结构化并发，并开启一个能够存活超过当前作用范围的新任务。。这个工具就是 Task.init(priority:operation:) 初始化方法。我们通常使用尾随闭包的语法来调用这个初始化方法.

```
let task = Task {
	return try await loadEpisodesAndCollections()
}
```
调用 Task.init 会开启一个新的独立任务，它的生命周期不和当前作用范围绑定。这个任务会立即开始，并和原来的任务并发运行。新任务会变成另一棵任务树的根节点，一直运行到任务结束。由于这个新任务和原来的任务并没有父子关系，所以我们将这类并发叫做非结构化并发。
